[target.thumbv7em-none-eabihf]
# add `-d cpu,guest_errors` to debug guest errors
# runner = "qemu-system-arm -cpu cortex-m7 -machine mps2-an500 -nographic -semihosting-config enable=on,target=native -kernel"
#runner = "arch gdb-multiarch -q -x openocd.gdb"
# runner = "probe-rs run --chip STM32h753zitx --probe 0483:374e:0026003E3233511239363634" # main
# runner = "probe-rs run --chip STM32h753zitx --probe 0483:374e:002D004E3532511331333430" # CAN sender
#  runner = "probe-rs run --chip STM32h753zitx --probe 0483:374e:0032002F3133510537363734"
# runner = "probe-rs run --chip STM32h743zitx --probe 0483:3754:001D00293033510735393935" # Thijs' main PCB
# runner = "probe-rs run --chip STM32h753zitx --probe 0483:374e:002600333133510936303739"
runner = "probe-rs run --chip STM32h753zitx --probe 0483:374e:001C00323233511039363634"


[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [
  "-C", "linker=flip-link",
]

[env]
DEFMT_LOG = "info"

[rust]
debug-assertions = true
