[target.thumbv7em-none-eabihf]
# add `-d cpu,guest_errors` to debug guest errors
runner = "probe-rs run --chip STM32H753ZITx"
# runner = "gdb -q -x openocd.gdb"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [
  "-C", "linker=flip-link",
  "-C", "instrument-coverage",
]

[build]
# Pick ONE of these default compilation targets
# target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+
# target = "thumbv7m-none-eabi"        # Cortex-M3
# target = "thumbv7em-none-eabi"       # Cortex-M4 and Cortex-M7 (no FPU)
target = "thumbv7em-none-eabihf"     # Cortex-M4F and Cortex-M7F (with FPU)
# target = "thumbv8m.base-none-eabi"   # Cortex-M23
# target = "thumbv8m.main-none-eabi"   # Cortex-M33 (no FPU)
# target = "thumbv8m.main-none-eabihf" # Cortex-M33 (with FPU)

[env]
DEFMT_LOG = "info"

[rust]
debug-assertions = true
