# -----------General COMMANDS-----------

[[Command]]
name = "DefaultCommand"
id = 0x01

[[Command]]
name = "Heartbeat"
id = 0x042

[[Command]]
name = "FrontendHeartbeat"
id = 0x043

[[Command]]
name = "EmitEvent"
id = 0x7A0


# -----------HIGH VOLTAGE COMMANDS-----------

[[Command]]
name = "StartHV"
id = 0x60

[[Command]]
name = "StopHV"
id = 0x61


# -----------LEVITATION COMMANDS-----------

[[Command]]
name = "LevitationOn"
id = 0x407

[[Command]]
name = "LevitationOff"
id = 0x408

[[Command]]
name = "vertical_0_current"
id = 0x409

[[Command]]
name = "vert_0_current_reset"
id = 0x40a


# -----------PROPULSION COMMANDS-----------

[[Command]]
name = "PropulsionOn"
id = 0x6c

[[Command]]
name = "PropulsionOff"
id = 0x6d

[[Command]]
name = "PropulsionStart"
id = 0x6e


# -----------RUN CONFIGURATION COMMANDS-----------

# Just one for submit run??
[[Command]]
name = "SubmitRunConfig"
id = 0x592

#[[Command]]
#name = "SetDirection"
#id = 0x590

#[[Command]]
#name = "SetSpeed"
#id = 0x591


# -----------CONTROL COMMANDS-----------

[[Command]]
name = "ArmBrakes"
id = 0x69

[[Command]]
name = "Shutdown"
id = 0x5f

[[Command]]
name = "EmergencyBrake"
id = 0xff

[[Command]]
name = "SystemReset"
id = 0x66




# Override events
# these are not part of the main control flow, but allow for either 
# debugging or other similarly useful functionality.

#[[Command]]
#name = "DcOff"
#id = 0x64
#
#[[Command]]
#name = "DcOn"
#id = 0x65
#
# [[Command]]
# name = "OpenContactor"
# id = 0x62
#
# [[Command]]
# name = "CloseContactor"
# id = 0x63
#
#[[Command]]
#name = "SetCurrentSpeed"
#id = 0x5a
#
#[[Command]]
#name = "CreateDatapoint"
#id = 0x5b
