[[Event]]
name = "NoEvent"
doc = "No event happened"

[[Event]]
name = "ConnectToGS"
doc = "Connection to the Ground Station has been established"

[[Event]]
name = "StartSystemCheck"
doc = "Start system check"

[[Event]]
name = "SystemCheckSuccess"
doc = "System was checked successfully"

[[Event]]
name = "EnterIdle"
doc = "Enters `Idle` state from `Discharge` state"

[[Event]]
name = "StartPreCharge"
doc = "Starts the pre-charging process"

[[Event]]
name = "Activate"
doc = "Will turn on high voltage while SDC is closed and brakes are deployed"

[[Event]]
name = "EnterDemo"
doc = "Enters the demo state armed brakes, SDC still closed"

[[Event]]
name = "Levitate"
doc = "Starts levitating"

[[Event]]
name = "StopLevitating"
doc = "Stops levitating"

[[Event]]
name = "Accelerate"
doc = "Starts accelerating until it reaches the target speed"

[[Event]]
name = "Cruise"
doc = "Stops accelerating"

[[Event]]
name = "Brake"
doc = "Deploys brakes"

[[Event]]
name = "Stopped"
doc = "Used for transitioning from braking to levitating when the speed of the pod is 0"

[[Event]]
name = "Discharge"
doc = "Starts discharging the high voltage batteries"

[[Event]]
name = "ShutDown"
doc = "Shuts down the pod"

[[Event]]
name = "Charge"
doc = "Pod should start charging"

[[Event]]
name = "StopCharge"
doc = "Pod should stop charging"

[[Event]]
name = "ResetFSM"
doc = "Resets the FSM to the `Boot` state"

[[Event]]
name = "StopFSM"
doc = "Stops the FSM"

[[Event]]
name = "Fault"
doc = "Fault happened"

[[Event]]
name = "Emergency"
doc = "Emergency event that must trigger the emergency braking system"

[[Event]]
name = "FaultFixed"
doc = "Used to transition from `Fault` to `SystemCheck` when the fault is fixed and no reboot is required"

[[Event]]
name = "HighVoltageOnCanRelay"
doc = ""

[[Event]]
name = "FSMTransition"
doc = "Event sent when transitioning. Used to send the `FSMUpdate` CAN message."
